version: "3.9"
services:
    client:
        build: ./client/whimsicalities
        ports:
            - "8080:80"
    server:
      build: ./server/whimsicalities-server
      ports:
        - "3000:3000"