# Build images and run for development/testing purposes
services:
    client:
      build: ./client/whimsicalities
      ports:
        - "80:80"
    server:
      build: ./server/whimsicalities-server
      ports:
        - "3000:3000"
      depends_on:
        redis:
          condition: service_healthy
      links:
        - redis
        - postgres
      environment:
        SECRETS_PATH: "/run/secrets/secrets.json"
        PORT: 3000
        REDIS_URL: "redis://@redis:6379"
        DECAY_SPEED_SECONDS: 60
      secrets:
        - source: secrets_json
          target: "secrets.json"
    redis:
      image: "redis:7.2.5"
      ports:
        - "6379:6379" # This is exposed so that the client and server can be run locally outside of containers
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 1s
        timeout: 2s
        retries: 10
      volumes:
        - redis_data:/data
    postgres:
      image: "postgres:17"
      restart: always
      environment:
        POSTGRES_PASSWORD: example
      volumes:
        - postgres_data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
    postgres-adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
      links:
        - postgres

volumes:
  redis_data:
  postgres_data:

secrets:
  secrets_json:
    file: ./secrets/test.secrets.json