# Pull images from repository and deploy. Used for actual deployment to the server.
services:
    client:
      image: "whimsicalities/personal-site:whimsicalities-client"
      ports:
        - "80:80"
    server:
      image: "whimsicalities/personal-site:whimsicalities-server"
      ports:
        - "3000:3000"
      depends_on:
        redis:
          condition: service_healthy
      links:
        - redis
        - postgres
      environment:
        SECRETS_PATH: "/run/secrets/secrets.json" # A file will be created that contains the secrets
        PORT: 3000
        REDIS_URL: "redis://@redis:6379"
        DECAY_SPEED_SECONDS: 3600
      secrets:
        - source: secrets_json
          target: "secrets.json" # Create the secrets file with this name
    redis:
      image: "redis:7.2.5"
      # Redis ports aren't exposed
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 1s
        timeout: 2s
        retries: 10
      volumes:
        - redis_data:/data
    postgres:
      image: "postgres:17"
      restart: always
      environment:
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD # From .env file
      volumes:
        - postgres_data:/var/lib/postgresql/data
      ports:
        - "5432:5432" # Access to 5432 should be ip-restricted
    postgres-adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080 # Access to 8080 should be ip-restricted
      links:
        - postgres

volumes:
  redis_data:
  postgres_data:

secrets:
  secrets_json:
    file: ./secrets/production.secrets.json