# Build images and run for development/testing purposes
services:
    client:
      build: ./client/whimsicalities
      ports:
        - "8080:80"
    server:
      build: ./server/whimsicalities-server
      ports:
        - "3000:3000"
      depends_on:
        redis:
          condition: service_healthy
      links:
        - redis
      environment:
        SECRETS_PATH: "/run/secrets/secrets.json"
      secrets:
        - source: secrets_json
          target: "secrets.json"
    redis:
      image: "redis:7.2.5"
      ports:
        - "6379:6379" # This is exposed so that the client and server can be run locally outside of containers
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 1s
        timeout: 2s
        retries: 10
      volumes:
        - redis_data:/data

volumes:
  redis_data:

secrets:
  secrets_json:
    file: ./secrets/test.secrets.json